### ISSUE TITLE
*555# Wikipedia, Serch crashes Server when something gets searched

### ISSUE THREAD

**Issue by HammiKnuff** [bildschirmtext/bildschirmtext#11]

**Comment by HammiKnuff** [comment]
I searched "Schönberger Strand" and it crashes.

**Comment by HammiKnuff** [comment]
Kulturdenkmäler Altona crashes also. Maybe because of so many tables?

**Comment by mist64** [comment]
In both cases, the search had no result. Fixed in 10833fcdc0ed6af12d12a7aca342d0ee86485ad6, now the system shows an error message if there are no results.
