### ISSUE TITLE
Entering wrong page number beginning with *55 crashes Server

### ISSUE THREAD

**Issue by HammiKnuff** [bildschirmtext/bildschirmtext#15]
Entering wrong page number beginning with *55 crashes Server

**Comment by Casandro** [comment]
I can confirm that:

Neu-Ulm running.
showing page: '00000a'
compressed 497 down to 323
Sending pal/char: .OK
Sending text: .....................................OK
history: ['00000a']
links: {}
In: 0x1c
s: None
In: 0x1c
s: None
In: 0x1c
s: 'call:Login_UI.callback_login'
login ok
input_data: {'$command': '000001a'}
showing page: '000001a'
loading: '../data/00000/a.inc'
Sending pal/char: .........OK
Sending text: ........................................OK
history: ['00000a', '000001a']
links: {'#': '0', '7': '77', '8': '88'}
In: 0x1c
s: None
input_data: {'$navigation': ''}
s: '0'
showing page: '0a'
filename: 'a'
loading: '../data/0/a.inc'
Sending pal/char: .........OK
Sending text: ....................................OK
history: ['00000a', '000001a', '0a']
links: {'6': '10401131', '7': '78', '8': '8', '9': '9'}
In: 0x13
entering command mode
In: 0x35
In: 0x35
In: 0x30
In: 0x1c
exited command mode
'<INI>550'
input_data: {'$command': '550'}
showing page: '550a'
URL: '../data/55/wikipedia.png'
mode: RGB, resolution: 729*696
target colors: 4
char resolution:   10*9, error: 0.02464392803598181
DRCs compressed 3600 down to 1468
Traceback (most recent call last):
  File "neu-ulm.py", line 585, in <module>
    ret = create_page(desired_pageid)
  File "neu-ulm.py", line 250, in create_page
    ret = MediaWiki_UI.create_page(pageid, basedir)
  File "/usr/src/bildschirmtext/server/wikipedia.py", line 428, in create_page
    return MediaWiki_UI.create_search_page(mediawiki, basedir)
  File "/usr/src/bildschirmtext/server/wikipedia.py", line 382, in create_search_page
    data_cept.extend(Cept.set_cursor(y, int((41 - len(chars[0])) / 2)))
NameError: name 'chars' is not defined

**Comment by Casandro** [comment]
I've been able to fix this partially by making 2 tiny fixes. Unfortunately I don't have write access.

**Comment by mist64** [comment]
You have been added. :)

**Comment by Casandro** [comment]
Thanks, it should work somewhat better now. I've added some checks for image and image.chars
